name: CI

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Build
        run: cargo build --release

      - name: Get current time
        uses: 1466587594/current-time@v1
        id: current-time
        with:
          format: YYYYMMDD_HHmmss
          utcOffset: "+08:00"

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: fgit-amd64-linux-${{ steps.current-time.outputs.formattedTime }}
          path: ./target/release/fgit

  build-win:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Build
        run: cargo build --release

      - name: Get current time
        uses: 1466587594/current-time@v1
        id: current-time
        with:
          format: YYYYMMDD_HHmmss
          utcOffset: "+08:00"

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: fgit-amd64-windows-${{ steps.current-time.outputs.formattedTime }}
          path: ./target/release/fgit.exe